name: CrearJsons

on:
  schedule:
    - cron: '0 6 * * 6'  # Every Saturday at 6:00 UTC

jobs:
  cleanup-img:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Remove all files in img folders except .gitkeep
        run: |
          find . -type d -name img | while read dir; do
            find "$dir" -type f ! -name '.gitkeep' -delete
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Cleanup: cleared img folders (excluding .gitkeep)" || echo "Nothing to commit"
          git push
        env:
          # Needed for push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

